import AuthProvider from "@/components/layouts/providers";
import "./../globals.css";
import "./../style.css"
import SideBar from "./_components/sidebar";
import NavMenu from "./_components/nav-menu";
import { Toaster } from "@/components/ui/toaster";
import { ReduxProviders } from "@/components/layouts/redux-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: 'Alarm | Administration',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ReduxProviders>
          <AuthProvider>
              <EdgeStoreProvider>
            <NavMenu />
              
            <div className="flex h-screen overflow-hidden">
              <SideBar />
              <Toaster />
              <main className="w-full pt-16">
                {children}
              </main>
            </div>
              </EdgeStoreProvider>  
          </AuthProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
