import AuthProvider from "@/components/layouts/providers";
import "./../globals.css";
import "./../style.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
      <body>
       <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  )
}
